var photoData = [
    {
        title: "Grineer Lancer",
        description: 'Created by Henchmen Studios, Character from game "Warframe"',
        date: "July 2019",
        imgUrl: "./img/grineerLancer.jpg", 
        classes: "h6 w4",
    },
    {
        title: "Ranger and Colossus",
        description: 'Created by Henchmen Studios for cinematic trailer of game "Anthem"',
        date: "July 2018",
        imgUrl: "./img/rangerAndColossus.jpg", 
        classes: "h4 w4",
    },
    {
        title: 'Destroy All Humans" Aliens',
        description: 'Created by Henchmen Studios, Characters from game "Destroy All Humans"',
        date: "June 2019",
        imgUrl: "./img/aliensDAH.jpg", 
        classes: "h3 w5",
    },
    {
        title: 'Pathfinder Robot',
        description: 'Created by Henchmen Studios, Character from game "Apex Legends"',
        date: "June 2019",
        imgUrl: "./img/pathfinder.jpg", 
        classes: "h5 w3",
    },
    {
        title: 'Nue Demon',
        description: 'Faux fur and stuffing with 3D printed teeth',
        date: "January 2019",
        imgUrl: "./img/nueDemon.jpg", 
        classes: "h2 w4",
    },
    {
        title: "Ape Hybrid",
        description: "Latex mask. Original design.",
        date: "November 2015",
        imgUrl: "./img/apeHybrid.jpg", 
        classes: "h3 w3",
    },
    {
        title: "Trevor the Turtle Man",
        description: "Multi-piece foam latex prosthetic. Original design. Created with Mary Catherine Lanzilotta, Alycia Boyd and Jas Sun.",
        date: "April 2016",
        imgUrl: "./img/turtleMan.jpg",
        classes: "h5 w3",
    },
    {
        title: "Zombie Cat Animatronic",
        description: "Animatronic, eyes and mouth move. Original design.",
        date: "Febuary 2016",
        imgUrl: "./img/kitty.jpg",
        classes: "h3 w3",
    },
    {
        title: "Bunny Puppet",
        description: "Original design.",
        date: "Febuary 2016",
        imgUrl: "./img/bunnyPuppet.jpg",
        classes: "h4 w3",
    },
    {
        title: "Zombie",
        description: "",
        date: "",
        imgUrl: "./img/zombie.jpg",
        classes: "h3 w2",
    },
    {
        title: "Burn Wound",
        description: "For film Here and Now.",
        date: "October 2017",
        imgUrl: "./img/burnFace1.jpg",
        classes: "h3 w3 rotateImg",
    },
    {
        title: "Alien Dinosaur",
        description: "Sculpey. Original Design based on Pegomastax Africanus dinosaur species",
        date: "August 2016",
        imgUrl: "./img/alienDinosaur.jpg",
        classes: "h3 w3",
    },
    {
        title: "Fox Mask",
        description: "Resin mask. Designed from Persona 5.",
        date: "October 2017",
        imgUrl: "./img/foxMask.jpg",
        classes: "h3 w3"
    },
    {
        title: "Joffrey Costume",
        description: "Costume design from Character Joffrey Baratheon from Game of Thrones",
        date: "February 2016",
        imgUrl: "./img/joffreyCosplay.jpg",
        classes: "h4 w2",
    },
    {
        title: "Swordfish Sword",
        description: "Worbla’s Finest Art and EVA foam. Original Design",
        date: "April 2016",
        imgUrl: "./img/fishSword.jpg",
        classes: "h2 w6",
    },
    {
        title: "Ghoul Character",
        description: "For interactive film for Blood and Snow film Festival.",
        date: "October 2017",
        imgUrl: "./img/ghostGuy.jpg",
        classes: "h3 w3",
    },
    {
        title: "Anders Costume",
        description: "Costume design from of character Anders from Dragon Age 2",
        date: "May 2015",
        imgUrl: "./img/andersCosplay.jpg",
        classes: "h4 w2",
    },
    {
        title: "Severed Finger",
        description: "Silicone",
        date: "March 2016",
        imgUrl: "./img/finger.jpg",
        classes: "h2 w2",
    },
    {
        title: "Burn Wound",
        description: "For film Here and Now.",
        date: "October 2017",
        imgUrl: "./img/burnFace2.jpg",
        classes: "h2 w2 rotateImg",
    },
    {
        title: "Bite Wound",
        description: "Pros-Aide Transfer. Sculpted, molded, cast and applied.",
        date: "April 2016",
        imgUrl: "./img/armBite.jpg",
        classes: "h2 w2",
    },
    {
        title: "Gelatin Wound",
        description: "Sculpted, molded, cast and applied.",
        date: "November 2015",
        imgUrl: "./img/armWound.jpg",
        classes: "h2 w2",
    },
    {
        title: "Silicone Wound",
        description: "Silicone transfer. Sculpted, molded, cast and applied.",
        date: "April 2016",
        imgUrl: "./img/armCut.jpg",
        classes: "h2 w2",
    },
    {
        title: "Baldcap Application",
        description: "For film From Me To You, Assisted by James Patterson.",
        date: "November 2015",
        imgUrl: "./img/face.jpg",
        classes: "h2 w2",
    },
]

var aboutText = `I am a special effects artist based in Toronto, ON. 
I graduated with honors from Sheridan College's Advanced Special Effects Makeup, Prosthetics and Props program in 2016. 
After graduating from the college's Visual and Creative Arts program in 2015
I first decided I wanted to create and bring characters to life through cosplaying, creating and wearing costumes of 
characters from popular media, where I discovered a love for costuming and propmaking. `;